name: Build pre-release
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out source code
        uses: actions/checkout@v3
        with:
          # needed to calc build number via git log --oneline
          fetch-depth: 0

      - name: Build
        run: .\doit.bat -build-pre-rel

      - name: upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sumatra-pdf-prerel
          path: out/final-prerel/
